import io
import zipfile
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from models.schemas import ExportRequest
from services.urdf_generator import generate_urdf_xacro, generate_srdf
from services.ros2_control_generator import generate_ros2_control
from services.moveit_generator import generate_moveit_config

router = APIRouter(tags=["export"])


@router.post("/export")
def export_robot(request: ExportRequest):
    """Generate and return a zip of all requested robot config files."""
    buf = io.BytesIO()
    name = request.robot_name

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        fmt = set(request.export_formats)

        if "urdf_xacro" in fmt or "urdf" in fmt:
            content = generate_urdf_xacro(request)
            zf.writestr(f"{name}/{name}.urdf.xacro", content)

        if "srdf" in fmt:
            content = generate_srdf(request)
            zf.writestr(f"{name}/{name}.srdf", content)

        if "ros2_control" in fmt:
            content = generate_ros2_control(request)
            zf.writestr(f"{name}/config/ros2_controllers.yaml", content)

        if "moveit_config" in fmt:
            files = generate_moveit_config(request)
            for filename, content in files.items():
                zf.writestr(f"{name}/config/{filename}", content)

        # Always include a README
        zf.writestr(f"{name}/README.md", _readme(request))

    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}_config.zip"'},
    )


def _readme(req: ExportRequest) -> str:
    joint_list = "\n".join(
        f"  - {j.linkName} ({j.manifest.type}, {j.manifest.displayName})"
        for j in req.joints
    )
    return f"""# {req.robot_name} — Robot Configuration

Generated by Cobot Configurator.

## Robot Structure
{len(req.joints)} joints:
{joint_list}

## Files
- `{req.robot_name}.urdf.xacro` — Main robot description (include in your ROS 2 package)
- `{req.robot_name}.srdf` — Semantic robot description for MoveIt 2
- `config/ros2_controllers.yaml` — ros2_control controller configuration
- `config/kinematics.yaml` — MoveIt kinematics plugin config
- `config/joint_limits.yaml` — Joint limits for MoveIt planning

## Usage
```bash
# In your ROS 2 workspace
colcon build
ros2 launch {req.robot_name} robot.launch.py
```
"""
