import os
from pathlib import Path
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
import io
import zipfile

from models.schemas import ExportRequest
from services.urdf_generator import generate_urdf_xacro, generate_srdf
from services.ros2_control_generator import generate_ros2_control
from services.moveit_generator import generate_moveit_config

router = APIRouter(tags=["export"])

JOINT_LIBRARY = Path(__file__).parent.parent.parent.parent / "packages" / "joint-library"


@router.post("/export")
def export_robot(request: ExportRequest):
    buf  = io.BytesIO()
    name = request.robot_name

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        fmt = set(request.export_formats)

        # ── Main robot URDF ──────────────────────────────────────────────────
        if "urdf_xacro" in fmt or "urdf" in fmt:
            zf.writestr(f"{name}/{name}.urdf.xacro", generate_urdf_xacro(request))

        if "srdf" in fmt:
            zf.writestr(f"{name}/{name}.srdf", generate_srdf(request))

        if "ros2_control" in fmt:
            zf.writestr(f"{name}/config/ros2_controllers.yaml", generate_ros2_control(request))

        if "moveit_config" in fmt:
            for filename, content in generate_moveit_config(request).items():
                zf.writestr(f"{name}/config/{filename}", content)

        # ── Per-joint XACRO files ─────────────────────────────────────────────
        # Each unique joint type gets its own folder in the zip matching the
        # expected ROS 2 package structure: {joint_id}_description/urdf/
        seen_joint_types: set[str] = set()
        for joint in request.joints:
            jid = joint.manifest.id
            if jid in seen_joint_types:
                continue
            seen_joint_types.add(jid)

            joint_dir = JOINT_LIBRARY / "joints" / jid / "urdf"
            if not joint_dir.exists():
                continue

            # Copy every file in the joint's urdf/ folder
            for file in joint_dir.rglob("*"):
                if file.is_file():
                    rel = file.relative_to(JOINT_LIBRARY / "joints" / jid)
                    zf.write(file, f"{jid}_description/{rel}")

        zf.writestr(f"{name}/README.md", _readme(request))

    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}_config.zip"'},
    )


def _readme(req: ExportRequest) -> str:
    joint_list = "\n".join(
        f"  - {j.jointName} ({j.manifest.type}, {j.manifest.displayName})"
        for j in req.joints
    )
    return f"""# {req.robot_name} — Robot Configuration

Generated by Cobot Configurator.

## Robot Structure
{len(req.joints)} joints:
{joint_list}

## Files
- `{req.robot_name}.urdf.xacro` — Main robot description (include in your ROS 2 package)
- `{req.robot_name}.srdf` — Semantic robot description for MoveIt 2
- `config/ros2_controllers.yaml` — ros2_control controller configuration
- `config/kinematics.yaml` — MoveIt kinematics plugin config
- `config/joint_limits.yaml` — Joint limits for MoveIt planning

## Usage
```bash
# In your ROS 2 workspace
colcon build
ros2 launch {req.robot_name} robot.launch.py
```
"""
