'''
Export CORA Config files from configurator scene to zip.
this export includes:
- URDF XACRO for the robot
- SRDF for the robot
- ros2_control.xacro configuration for the robot
- Combined URDF of the robot
- Joint limits for MoveIt planning
- Kinematics configuration for MoveIt planning
- Servo Params
'''


import os
from pathlib import Path
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
import io
import zipfile

from models.schemas import ExportRequest
from services.urdf_generator import generate_urdf_xacro, generate_srdf
from services.ros2_control_generator import generate_ros2_control
from services.moveit_generator import generate_moveit_config
from config import JOINT_LIBRARY

router = APIRouter(tags=["export"])


# TODO: #8 BUG — the install DESTINATION below renders as the literal string
# "share/PROJECT_NAME": the $ and braces are missing. Should be
# share/${PROJECT_NAME}. The exported package installs to the wrong path.
def generate_cmake(robot_name: str) -> str:
    return f"""cmake_minimum_required(VERSION 3.8)
project({robot_name})

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(xacro REQUIRED)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # comment the line when a copyright and license is added to all source files
  set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # comment the line when this package is in a git repo and when
  # a copyright and license is added to all source files
  set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()


install(
  DIRECTORY
    urdf
    config
  DESTINATION share/${'PROJECT_NAME'}
)

ament_package()
"""


# TODO: #8 the generated package.xml declares only <depend>xacro</depend>.
# It needs the moveit / ros2_control / controller_manager deps, plus one
# <depend> per "<jid>_description" package the generated URDF includes.
# TODO: #8 the maintainer is hardcoded to a personal address; make it
# configurable. (Keep these notes OUT of the f-string below — a literal
# "{...}" in there is parsed as a format field and raises at runtime.)
def generate_package_xml(robot_name: str) -> str:
    return f"""<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
<name>{robot_name}</name>
<version>0.0.0</version>
<description>TODO: Package description</description>
<maintainer email="matthewdelannoy527@gmail.com">matth</maintainer>
<license>Apache-2.0</license>

<buildtool_depend>ament_cmake</buildtool_depend>

<depend>xacro</depend>

<test_depend>ament_lint_auto</test_depend>
<test_depend>ament_lint_common</test_depend>

<export>
    <build_type>ament_cmake</build_type>
</export>
</package>
"""


@router.post("/export")
def export_robot(request: ExportRequest):
    buf = io.BytesIO()
    name = request.robot_name

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        fmt = set(request.export_formats)

        # ── Main robot URDF ──────────────────────────────────────────────────
        if "urdf_xacro" in fmt or "urdf" in fmt:
            zf.writestr(f"{name}/urdf/{name}.urdf.xacro", generate_urdf_xacro(request))

        if "srdf" in fmt:
            zf.writestr(f"{name}/urdf/{name}.srdf", generate_srdf(request))

        if "ros2_control" in fmt:
            zf.writestr(
                f"{name}/config/ros2_controllers.yaml", generate_ros2_control(request)
            )

        # TODO: #2 emit config/robot_layout.yaml here — the contract that lets
        # cora_common stop hardcoding J1..J6 / endeffector / arm / arm_controller.
        # This blocks C-O-R-A/cora_common#1, #2 and #3.
        # TODO: #3 emit config/initial_positions.yaml (required for xacro to expand).
        # TODO: #9 emit launch/ and config/moveit.rviz — nothing is launchable today.
        if "moveit_config" in fmt:
            for filename, content in generate_moveit_config(request).items():
                zf.writestr(f"{name}/config/{filename}", content)
        zf.writestr(f"{name}/README.md", _readme(request))

    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{name}_config.zip"'},
    )


def _readme(req: ExportRequest) -> str:
    joint_list = "\n".join(
        f"  - {j.jointName} ({j.manifest.joint_type}, {j.manifest.displayName})"
        for j in req.joints
    )
    return f"""# {req.robot_name} — Robot Configuration

Generated by CORA Configurator.

## Robot Structure
{len(req.joints)} joints:
{joint_list}

## Files
- `{req.robot_name}.urdf.xacro` — Main robot description (include in your ROS 2 package)
- `{req.robot_name}.srdf` — Semantic robot description for MoveIt 2
- `config/ros2_controllers.yaml` — ros2_control controller configuration
- `config/kinematics.yaml` — MoveIt kinematics plugin config
- `config/joint_limits.yaml` — Joint limits for MoveIt planning

## Usage
```bash
# In your ROS 2 workspace
colcon build
ros2 launch {req.robot_name} robot.launch.py
```
"""
