import type { JointManifest } from '../types/manifest'

// Mock data used when the backend is not running.
// Meshes reference placeholder geometry built in the viewer itself.
export const MOCK_JOINTS: JointManifest[] = [
  {
    id: 'revolute_80mm',
    type: 'revolute',
    displayName: 'Revolute 80mm',
    description: 'Compact revolute joint with 80mm output flange',
    version: '1.0.0',
    params: {
      flange_diameter: 80,
      housing_diameter: 86,
      length: 65,
      mass: 0.85,
      inertia_ixx: 0.001,
      inertia_iyy: 0.001,
      inertia_izz: 0.0005,
      max_torque: 120,
      max_speed: 180,
    },
    mesh: { visual: 'placeholder', collision: 'placeholder' },
    frames: {
      parent_attach: [0, 0, 0],
      child_attach: [0, 0, 65],
      motor_mount: [0, 0, 10],
    },
    axis: [0, 0, 1],
    motor_interface: {
      type: 'shaft',
      shaft_diameter: 10,
      flange_bolt_circle: 60,
      bolt_count: 4,
      bolt_size: 'M5',
      max_motor_diameter: 60,
      max_motor_length: 80,
    },
    gearbox: { integrated: false, type: 'none' },
    cad_script: 'revolute_80mm.py',
    tags: ['revolute', 'compact', 'series-80'],
  },
  {
    id: 'revolute_120mm',
    type: 'revolute',
    displayName: 'Revolute 120mm',
    description: 'High-torque revolute joint with 120mm output flange',
    version: '1.0.0',
    params: {
      flange_diameter: 120,
      housing_diameter: 130,
      length: 90,
      mass: 1.8,
      inertia_ixx: 0.004,
      inertia_iyy: 0.004,
      inertia_izz: 0.002,
      max_torque: 350,
      max_speed: 120,
    },
    mesh: { visual: 'placeholder', collision: 'placeholder' },
    frames: {
      parent_attach: [0, 0, 0],
      child_attach: [0, 0, 90],
      motor_mount: [0, 0, 15],
    },
    axis: [0, 0, 1],
    motor_interface: {
      type: 'hollow',
      bore_diameter: 25,
      flange_bolt_circle: 95,
      bolt_count: 6,
      bolt_size: 'M6',
      max_motor_diameter: 90,
      max_motor_length: 120,
    },
    gearbox: { integrated: true, ratio: 50, type: 'harmonic' },
    cad_script: 'revolute_120mm.py',
    tags: ['revolute', 'high-torque', 'series-120'],
  },
  {
    id: 'prismatic_100mm',
    type: 'prismatic',
    displayName: 'Prismatic 100mm',
    description: 'Linear prismatic joint, 100mm stroke',
    version: '1.0.0',
    params: {
      flange_diameter: 60,
      housing_diameter: 60,
      length: 180,
      mass: 1.1,
      inertia_ixx: 0.002,
      inertia_iyy: 0.002,
      inertia_izz: 0.0003,
      max_force: 800,
      stroke: 100,
      max_speed: 200,
    },
    mesh: { visual: 'placeholder', collision: 'placeholder' },
    frames: {
      parent_attach: [0, 0, 0],
      child_attach: [0, 0, 180],
    },
    axis: [0, 0, 1],
    motor_interface: {
      type: 'shaft',
      shaft_diameter: 8,
      flange_bolt_circle: 45,
      bolt_count: 4,
      bolt_size: 'M4',
      max_motor_diameter: 42,
      max_motor_length: 80,
    },
    gearbox: { integrated: false, type: 'none' },
    cad_script: 'prismatic_100mm.py',
    tags: ['prismatic', 'linear'],
  },
  {
    id: 'universal_60mm',
    type: 'universal',
    displayName: 'Universal 60mm',
    description: 'Universal joint for 2-DOF wrist applications',
    version: '1.0.0',
    params: {
      flange_diameter: 60,
      housing_diameter: 72,
      length: 80,
      mass: 0.6,
      inertia_ixx: 0.0008,
      inertia_iyy: 0.0008,
      inertia_izz: 0.0004,
      max_torque: 45,
      max_speed: 240,
    },
    mesh: { visual: 'placeholder', collision: 'placeholder' },
    frames: {
      parent_attach: [0, 0, 0],
      child_attach: [0, 0, 80],
    },
    axis: [0, 1, 0],
    motor_interface: {
      type: 'flat',
      flange_bolt_circle: 48,
      bolt_count: 4,
      bolt_size: 'M4',
      max_motor_diameter: 42,
      max_motor_length: 60,
    },
    tags: ['universal', 'wrist', 'series-60'],
  },
]
